name: Deploy Auth Service

on:
  push:
    branches:
      - main
    paths:
      - 'notification-system/auth-service/**'
      - 'notification-system/shared/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Set deployment directory
            DEPLOY_DIR="/opt/notification-system"
            
            # Clone or update repository
            if [ ! -d "$DEPLOY_DIR" ]; then
              echo "📦 Cloning repository for the first time..."
              git clone https://github.com/${{ github.repository }}.git $DEPLOY_DIR
              cd $DEPLOY_DIR
            else
              echo "🔄 Updating repository..."
              cd $DEPLOY_DIR
              git fetch origin
              git reset --hard origin/main
              git pull origin main
            fi
            
            # Navigate to service directory and deploy
            cd notification-system/auth-service
            chmod +x deploy.sh
            ./deploy.sh
